//2024年度用
import 'package:kenryo_tankyu/models/models.dart';

final List<Teacher> teacherList = [
  Teacher(
      id: '24001',
      name: '押野佳明',
      nameKana: 'おしのよしあき',
      subject: SubjectType.japanese,
      grade: GradeInCharge.second),
  Teacher(
      id: '24002',
      name: '雨宮明弘',
      nameKana: 'あめみやあきひろ',
      subject: SubjectType.japanese,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24003',
      name: '岩原伸',
      nameKana: 'いわはらしん',
      subject: SubjectType.japanese,
      grade: GradeInCharge.second),
  Teacher(
      id: '24004',
      name: '日下部英司',
      nameKana: 'くさかべえいじ',
      subject: SubjectType.japanese,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24005',
      name: '小寺麻衣',
      nameKana: 'こでらまい',
      subject: SubjectType.japanese,
      grade: GradeInCharge.third),
  Teacher(
      id: '24006',
      name: '齋藤亮',
      nameKana: 'さいとうりょう',
      subject: SubjectType.japanese,
      grade: GradeInCharge.third),
  Teacher(
      id: '24007',
      name: '関正浩',
      nameKana: 'せきまさひろ',
      subject: SubjectType.japanese,
      grade: GradeInCharge.first),
  Teacher(
      id: '24008',
      name: '武居寿都',
      nameKana: 'たけいかずと',
      subject: SubjectType.japanese,
      grade: GradeInCharge.first),
  Teacher(
      id: '24009',
      name: '成田亜矢子',
      nameKana: 'なりたあやこ',
      subject: SubjectType.japanese,
      grade: GradeInCharge.first),
  Teacher(
      id: '24010',
      name: '金澤大典',
      nameKana: 'かなざわだいすけ',
      subject: SubjectType.social,
      grade: GradeInCharge.second),
  Teacher(
      id: '24011',
      name: '小松真之',
      nameKana: 'こまつまさゆき',
      subject: SubjectType.social,
      grade: GradeInCharge.third),
  Teacher(
      id: '24012',
      name: '塩原浩',
      nameKana: 'しおはらひろし',
      subject: SubjectType.social,
      grade: GradeInCharge.first),
  Teacher(
      id: '24013',
      name: '染野雄太郎',
      nameKana: 'そめのゆうたろう',
      subject: SubjectType.social,
      grade: GradeInCharge.second),
  Teacher(
      id: '24014',
      name: '武田邦秀',
      nameKana: 'たけだくにひで',
      subject: SubjectType.social,
      grade: GradeInCharge.third),
  Teacher(
      id: '24015',
      name: '野口智敬',
      nameKana: 'のぐちともひろ',
      subject: SubjectType.social,
      grade: GradeInCharge.second),
  Teacher(
      id: '24016',
      name: '福田圭佑',
      nameKana: 'ふくだけいすけ',
      subject: SubjectType.social,
      grade: GradeInCharge.first),
  Teacher(
      id: '24017',
      name: '壬生花菜',
      nameKana: 'みぶかな',
      subject: SubjectType.social,
      grade: GradeInCharge.first),
  Teacher(
      id: '24018',
      name: '宮坂正議',
      nameKana: 'みやさかまさよし',
      subject: SubjectType.social,
      grade: GradeInCharge.third),
  Teacher(
      id: '24019',
      name: '青木要二',
      nameKana: 'あおきようじ',
      subject: SubjectType.math,
      grade: GradeInCharge.first),
  Teacher(
      id: '24020',
      name: '上原雄貴',
      nameKana: 'うえはらゆうき',
      subject: SubjectType.math,
      grade: GradeInCharge.second),
  Teacher(
      id: '24021',
      name: '小澤健二',
      nameKana: 'おざわけんじ',
      subject: SubjectType.math,
      grade: GradeInCharge.second),
  Teacher(
      id: '24022',
      name: '近藤慎',
      nameKana: 'こんどうしん',
      subject: SubjectType.math,
      grade: GradeInCharge.third),
  Teacher(
      id: '24023',
      name: '塩原潤',
      nameKana: 'しおはらじゅん',
      subject: SubjectType.math,
      grade: GradeInCharge.third),
  Teacher(
      id: '24024',
      name: '福田孝子',
      nameKana: 'ふくだたかこ',
      subject: SubjectType.math,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24025',
      name: '百瀬裕也',
      nameKana: 'ももせひろや',
      subject: SubjectType.math,
      grade: GradeInCharge.first),
  Teacher(
      id: '24026',
      name: '湯川紳',
      nameKana: 'ゆかわしん',
      subject: SubjectType.math,
      grade: GradeInCharge.first),
  Teacher(
      id: '24027',
      name: '栢木駿輔',
      nameKana: 'かやきしゅんすけ',
      subject: SubjectType.math,
      grade: GradeInCharge.second),
  Teacher(
      id: '24028',
      name: '伊藤広昭',
      nameKana: 'いとうひろあき',
      subject: SubjectType.science,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24029',
      name: '小口聡',
      nameKana: 'おぐちさとし',
      subject: SubjectType.science,
      grade: GradeInCharge.other),
  Teacher(
      id: '24030',
      name: '春日隆史',
      nameKana: 'かすがたかし',
      subject: SubjectType.science,
      grade: GradeInCharge.third),
  Teacher(
      id: '24031',
      name: '勝家康太郎',
      nameKana: 'かついえこうたろう',
      subject: SubjectType.science,
      grade: GradeInCharge.third),
  Teacher(
      id: '24032',
      name: '久保田宏',
      nameKana: 'くぼたひろし',
      subject: SubjectType.science,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24033',
      name: '小林晃平',
      nameKana: 'こばやしこうへい',
      subject: SubjectType.science,
      grade: GradeInCharge.first),
  Teacher(
      id: '24034',
      name: '中村祐介',
      nameKana: 'なかむらゆうすけ',
      subject: SubjectType.science,
      grade: GradeInCharge.second),
  Teacher(
      id: '24035',
      name: '中村優介',
      nameKana: 'なかむらゆうすけ',
      subject: SubjectType.science,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24036',
      name: '西牧岳哉',
      nameKana: 'にしまきたけや',
      subject: SubjectType.science,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24037',
      name: '宮下達郎',
      nameKana: 'みやしたたつろう',
      subject: SubjectType.science,
      grade: GradeInCharge.third),
  Teacher(
      id: '24038',
      name: '森田純子',
      nameKana: 'もりたじゅんこ',
      subject: SubjectType.science,
      grade: GradeInCharge.second),
  Teacher(
      id: '24039',
      name: '山田みゆき',
      nameKana: 'やまだみゆき',
      subject: SubjectType.science,
      grade: GradeInCharge.first),
  Teacher(
      id: '24040',
      name: '臼井柊',
      nameKana: 'うすいしゅう',
      subject: SubjectType.pe,
      grade: GradeInCharge.second),
  Teacher(
      id: '24041',
      name: '佐藤賢一',
      nameKana: 'さとうけんいち',
      subject: SubjectType.pe,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24042',
      name: '杉本哲敏',
      nameKana: 'すぎもとあきとし',
      subject: SubjectType.pe,
      grade: GradeInCharge.first),
  Teacher(
      id: '24043',
      name: '竹田さゆり',
      nameKana: 'たけださゆり',
      subject: SubjectType.pe,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24044',
      name: '鰐川怜児',
      nameKana: 'わにかわれいじ',
      subject: SubjectType.pe,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24045',
      name: '渡邉亜希子',
      nameKana: 'わたなべあきこ',
      subject: SubjectType.art,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24046',
      name: '滝沢美穂',
      nameKana: 'たきざわみほ',
      subject: SubjectType.art,
      grade: GradeInCharge.third),
  Teacher(
      id: '24047',
      name: '大月美歩',
      nameKana: 'おおつきみほ',
      subject: SubjectType.art,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24048',
      name: '赤塩絵理',
      nameKana: 'あかしおえり',
      subject: SubjectType.english,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24049',
      name: '赤羽紗也子',
      nameKana: 'あかはねさやこ',
      subject: SubjectType.english,
      grade: GradeInCharge.first),
  Teacher(
      id: '24050',
      name: '市川安以',
      nameKana: 'いちかわあい',
      subject: SubjectType.english,
      grade: GradeInCharge.second),
  Teacher(
      id: '24051',
      name: '郷原俊一',
      nameKana: 'ごうはらしゅんいち',
      subject: SubjectType.english,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24052',
      name: '竹岡康太',
      nameKana: 'たけおかこうた',
      subject: SubjectType.english,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24053',
      name: '羽賀規真',
      nameKana: 'はがのりまさ',
      subject: SubjectType.english,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24054',
      name: '藤原未幸',
      nameKana: 'ふじわらみゆき',
      subject: SubjectType.english,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24055',
      name: '中村真由美',
      nameKana: 'なかむらまゆみ',
      subject: SubjectType.english,
      grade: GradeInCharge.third),
  Teacher(
      id: '24056',
      name: '鵜野亜矢子',
      nameKana: 'うのあやこ',
      subject: SubjectType.english,
      grade: GradeInCharge.first),
  Teacher(
      id: '24057',
      name: 'Jason Smith',
      nameKana: 'JasonSmith',
      subject: SubjectType.english,
      grade: GradeInCharge.second),
  Teacher(
      id: '24058',
      name: '山田智恵',
      nameKana: 'やまだちえ',
      subject: SubjectType.home,
      grade: GradeInCharge.second),
  Teacher(
      id: '24059',
      name: '関孝誠',
      nameKana: 'せきこうせい',
      subject: SubjectType.information,
      grade: GradeInCharge.unknown),
  Teacher(
      id: '24060',
      name: '宮木慧美',
      nameKana: 'みやきさとみ',
      subject: SubjectType.tankyu,
      grade: GradeInCharge.other),
];

//enum 定義
